# Generated by Django 5.1 on 2024-09-02 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=50)),
                ('employment_status', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contractual', 'Contractual'), ('permanent', 'Permanent')], max_length=20)),
                ('job_context', models.TextField()),
                ('job_responsibilities', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('other_benefits', models.TextField(blank=True, null=True)),
                ('job_posted_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('application_instructions', models.TextField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='employer.employer')),
                ('job_category', models.ManyToManyField(related_name='job_category', to='job_catagory.category')),
            ],
        ),
    ]
